### ISSUE TITLE
Builder page is not editable on first load

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#29]
We are using builder to manage a content section on pages within our app. When we load a builder page, we also load our app into the editor so we can full WYSIWYG experience.

However, when we first load the builder page into your editor, it takes several refreshes for the builder page to become editable.

**Comment by steve8708** [comment]
@JefferyReidKnowde does this still happen to you, and if so could you add more steps to reproduce? I tried to reproduce using the Knowde staging setup and wasn't able to

**Comment by JefferyReidKnowde** [comment]
@steve8708 
Yes. Still seeing the issue. Here's a video
https://www.dropbox.com/s/jgm43a8vlpuio7t/2020-01-16_14-14-42.mp4?dl=0

**Comment by lyczos** [comment]
@steve8708 it also happened to me today and i can not edit pages until I load fallback editor
https://drive.google.com/file/d/1McWe03SP90UG517U8kZcvNAMCESIt78e/view

**Comment by steve8708** [comment]
Sorry to bother with the same question again - but I'm trying to reproduce and failing to, so wanted to double verify that this is still happening before spending more time diving in to ways to reproduce

**Comment by steve8708** [comment]
nevermind - got it to happen! taking a look

**Comment by steve8708** [comment]
Believe I may have fixed this - it's a tricky one bc it seems to happen semi randmoly for me - but could one of you try reproducing on `beta.builder.io` and let me know if this happens there? If so I'll deploy the fix to production

**Comment by steve8708** [comment]
Doing a lot of testing without being able to reproduce any longer and believe this is fixed. Going to close out but please reopen if this happens to you again on beta.builder.io (should go to production builder.io later this week)

**Comment by JefferyReidKnowde** [comment]
Thanks. Once it’s in prod, we will confirm back. Currently, it’s happening often


Jeffery Reid | Chief Product Officer | Knowde | Mobile: 206-612-7009 | www.knowde.com

https://calendly.com/jefferyreid

**Comment by steve8708** [comment]
Sounds good @JefferyReidKnowde . Just pushed to prod, things should be improved now (potentially after a refresh once or twice to be on latest code). Let us know if you have any more issues here or elsewhere

**Comment by steve8708** [comment]
Reopening bc I see from @JefferyReidKnowde this has still been happening - @lyczos can you try out `@builder.io/angular@1.0.83-alpha.2` and let me know if the problem still happens to you there?

**Comment by ca136** [comment]
@JefferyReidKnowde @lyczos I tried reproducing this again on the pages from your video and haven't seen the issue yet. Just wanted to confirm you are still seeing this with the most recent Angular SDK?

**Comment by steve8708** [comment]
Update here -I see this is indeed happening for other angular users too (e.g. ShopStyle)

**Comment by JefferyReidKnowde** [comment]
This happens to me nearly every time on FirstOpen of a page. LMK if you need a more recent video or if you want to hop on a screen share so you can collect forensics on this

**Comment by ca136** [comment]
Hi @JefferyReidKnowde, I think we're able to consistently reproduce at this point, but if I need more information I'll definitely take you up on your offer.

It's next up on my list of things to look into, so hopefully will have a fix deployed maybe early next week.
